### ISSUE TITLE
v2.0 release?

### ISSUE THREAD

**Issue by schamberg97** [jkyberneees/low-http-server#5]
@jkyberneees , since we have merged two changes, one of them is breaking, I believe it is time to release a new major semantic version. Also, sorry for being rather slow, had some delays due to certain life changes

**Comment by jkyberneees** [comment]
Hi @schamberg97, thanks for your valuable and professional contributions. 
I totally agree. Will prepare the release.

**Comment by jkyberneees** [comment]
Done https://github.com/jkyberneees/low-http-server/releases 👌
